//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystemWEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugsInventory
    {
        public int DrugId { get; set; }
        public string DrugName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> SupplierId { get; set; }
    }
}
